-- Monthly recurring billing: periods with a lifecycle, persisted usage,
-- month-scoped approvals, and an audit trail.
--
-- Applied after schema.sql on the same cold-start path (db.init_db), and
-- idempotent for the same reason: every statement is IF NOT EXISTS or an
-- ADD COLUMN IF NOT EXISTS. Splitting it out of schema.sql keeps the original
-- file readable as "the validated reconciliation schema" and this one as
-- "what recurring operation added".
--
-- Dialect note: the existing schema stores timestamps as TEXT in
-- 'YYYY-MM-DD HH24:MI:SS' because those values are returned to the frontend as
-- strings and compared as strings. New columns keep that convention rather
-- than mixing TEXT and TIMESTAMPTZ in the same rows.

-- ------------------------------------------------------------ billing periods
-- `periods` already existed with label/name/basis/closed. It becomes the
-- billing period record rather than a new table, so the June 2026 row and every
-- existing foreign key survive. `closed` is kept in sync with status = 'CLOSED'
-- so nothing reading the old column silently changes meaning.
ALTER TABLE periods ADD COLUMN IF NOT EXISTS billing_type  TEXT NOT NULL DEFAULT 'ADHOC_PAPERWORK';
ALTER TABLE periods ADD COLUMN IF NOT EXISTS year          INTEGER;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS month         INTEGER;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS period_start  TEXT;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS period_end    TEXT;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS status        TEXT NOT NULL DEFAULT 'IN_REVIEW';
ALTER TABLE periods ADD COLUMN IF NOT EXISTS updated_at    TEXT;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS closed_at     TEXT;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS created_by    TEXT;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS run_source    TEXT;

-- Backfill the columns for any period that predates them. label is 'YYYY-MM'.
UPDATE periods
   SET year         = COALESCE(year,  CAST(SUBSTRING(label, 1, 4) AS INTEGER)),
       month        = COALESCE(month, CAST(SUBSTRING(label, 6, 2) AS INTEGER)),
       period_start = COALESCE(period_start, label || '-01'),
       period_end   = COALESCE(
                        period_end,
                        to_char(
                          (CAST(label || '-01' AS DATE) + INTERVAL '1 month' - INTERVAL '1 day'),
                          'YYYY-MM-DD')),
       updated_at   = COALESCE(updated_at, created_at)
 WHERE year IS NULL OR month IS NULL OR period_start IS NULL
    OR period_end IS NULL OR updated_at IS NULL;

-- A closed period must read as CLOSED whichever column you look at.
UPDATE periods SET status = 'CLOSED' WHERE closed = 1 AND status <> 'CLOSED';

-- One period per billing type per month. This is what makes "create or locate"
-- safe to call concurrently: the scheduled job and a manual run race to the
-- same row rather than making two.
CREATE UNIQUE INDEX IF NOT EXISTS idx_periods_type_month
  ON periods(billing_type, year, month);

-- `label` was globally UNIQUE when a period could only mean Ad Hoc Paperwork.
-- With a billing_type column that constraint says "no two billing products may
-- ever bill the same month", which is the opposite of the intent — adding
-- Worker Onboarding for July 2026 would fail against Ad Hoc's July 2026.
-- Uniqueness moves to (billing_type, label), so Ad Hoc's labels stay exactly as
-- unique as they were and a second product is possible.
ALTER TABLE periods DROP CONSTRAINT IF EXISTS periods_label_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_periods_type_label ON periods(billing_type, label);

-- Status is a closed set. A typo'd status would otherwise silently make a
-- period invisible to every status-filtered query.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'periods_status_check') THEN
    ALTER TABLE periods ADD CONSTRAINT periods_status_check
      CHECK (status IN ('PROCESSING', 'IN_REVIEW', 'READY_TO_BILL', 'CLOSED', 'FAILED'));
  END IF;
END $$;

-- --------------------------------------------------------------- usage events
-- The persisted, merged record of what was billable in a period. `events` is
-- still the pipeline's output for the current run; usage_events is the durable
-- layer that survives reruns and carries review state.
--
-- The natural key is (period, packet, worker, paperwork). packet_id alone is
-- not unique: one packet can cover several workers, and a worker can have
-- several paperwork types in the same packet — which is exactly why different
-- paperwork types stay separate billable events.
CREATE TABLE IF NOT EXISTS usage_events (
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id               INTEGER NOT NULL REFERENCES periods(id) ON DELETE CASCADE,
  billing_type            TEXT    NOT NULL DEFAULT 'ADHOC_PAPERWORK',

  -- source evidence, kept for audit
  packet_id               TEXT    NOT NULL,
  seso_worker_id          TEXT    NOT NULL,
  worker_name             TEXT,
  paperwork_name          TEXT    NOT NULL,
  sent_date               TEXT,
  signed_date             TEXT,
  sender_name             TEXT,
  source_customer         TEXT    NOT NULL,
  billing_customer        TEXT    NOT NULL,
  salesforce_account      TEXT,
  salesforce_account_id   TEXT,
  contract_name           TEXT,
  contract_ids            TEXT,
  source_record_ids       TEXT,               -- JSON: every source row that collapsed here
  duplicate_group_key     TEXT,               -- what made them the same event
  duplicate_source_count  INTEGER NOT NULL DEFAULT 1,
  duplicate_contracts     TEXT,               -- JSON: all contract names in the group

  -- classification carried from the pipeline
  csm                     TEXT,
  customer_mapping_applied INTEGER NOT NULL DEFAULT 0,
  mapping_reason           TEXT,
  sf_price                DOUBLE PRECISION,
  flag                    TEXT    NOT NULL,
  has_active              INTEGER NOT NULL DEFAULT 1,
  excluded                INTEGER NOT NULL DEFAULT 0,
  exclusion_reason        TEXT,

  -- merge / review bookkeeping
  qualification_status    TEXT    NOT NULL DEFAULT 'QUALIFIED',
  first_seen_run_id       INTEGER REFERENCES pipeline_runs(id),
  last_seen_run_id        INTEGER REFERENCES pipeline_runs(id),
  disqualified_at         TEXT,
  disqualified_reason     TEXT,
  reviewed                INTEGER NOT NULL DEFAULT 0,
  created_at              TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at              TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),

  -- This is the idempotency guarantee. Rerunning a month updates these rows;
  -- it cannot duplicate them.
  UNIQUE (period_id, packet_id, seso_worker_id, paperwork_name)
);

CREATE INDEX IF NOT EXISTS idx_usage_period   ON usage_events(period_id);
CREATE INDEX IF NOT EXISTS idx_usage_billing  ON usage_events(period_id, billing_customer);
CREATE INDEX IF NOT EXISTS idx_usage_acct     ON usage_events(period_id, salesforce_account_id);
CREATE INDEX IF NOT EXISTS idx_usage_qual     ON usage_events(period_id, qualification_status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'usage_events_qualification_check') THEN
    ALTER TABLE usage_events ADD CONSTRAINT usage_events_qualification_check
      CHECK (qualification_status IN ('QUALIFIED', 'NO_LONGER_QUALIFIES'));
  END IF;
END $$;

-- ------------------------------------------------- customer period summaries
-- Materialised per customer per period. For an OPEN period this is recomputed
-- from live pricing on every run and every price confirmation. For a CLOSED
-- period it is frozen: it keeps the unit price and pricing source the period
-- closed with, which is what stops a later override rewriting billed history.
CREATE TABLE IF NOT EXISTS customer_period_summaries (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id              INTEGER NOT NULL REFERENCES periods(id) ON DELETE CASCADE,
  billing_customer       TEXT    NOT NULL,
  salesforce_account_id  TEXT    NOT NULL DEFAULT '',
  salesforce_account     TEXT,
  csm                    TEXT,
  source_customers       TEXT,               -- JSON array
  billable_packets       INTEGER NOT NULL DEFAULT 0,
  workers                INTEGER NOT NULL DEFAULT 0,
  excluded_packets       INTEGER NOT NULL DEFAULT 0,
  unit_price             DOUBLE PRECISION,
  pricing_source         TEXT,
  sf_pricing_status      TEXT,
  expected_amount        DOUBLE PRECISION,
  pricing_status         TEXT    NOT NULL DEFAULT 'OK',      -- OK | CSM_CONFIRM_PRICE | CSM_CONFIRMED_PRICE
  exception_status       TEXT    NOT NULL DEFAULT 'NONE',    -- NONE | <blocking flag>
  blocking_exceptions    TEXT,               -- JSON array of flags
  review_status          TEXT    NOT NULL DEFAULT 'READY_TO_BILL',
  frozen                 INTEGER NOT NULL DEFAULT 0,
  created_at             TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at             TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  -- Not billing_customer alone: two legal entities can share an account, and an
  -- account can be blank for an unmatched customer.
  UNIQUE (period_id, billing_customer, salesforce_account_id)
);

CREATE INDEX IF NOT EXISTS idx_cps_period ON customer_period_summaries(period_id);

-- ------------------------------------------------------ Good to Bill approvals
-- Month-specific. A July approval must not approve August, which is why
-- period_id is part of the key rather than a column on the customer.
CREATE TABLE IF NOT EXISTS customer_period_approvals (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id              INTEGER NOT NULL REFERENCES periods(id) ON DELETE CASCADE,
  billing_customer       TEXT    NOT NULL,
  salesforce_account_id  TEXT    NOT NULL DEFAULT '',
  good_to_bill           INTEGER NOT NULL DEFAULT 0,
  approved_by            TEXT,               -- authenticated email, never free text
  approved_at            TEXT,
  revoked_by             TEXT,
  revoked_at             TEXT,
  note                   TEXT,
  UNIQUE (period_id, billing_customer, salesforce_account_id)
);

-- ------------------------------------------------------------- pricing overrides
-- price_overrides already held the CSM-confirmed layer. These columns make it
-- satisfy the persistence contract: effective window, active flag, billing type
-- and an explicit source. The primary key stays sf_account_id — one *active*
-- override per account — and history lives in audit_log, which is append-only.
ALTER TABLE price_overrides ADD COLUMN IF NOT EXISTS effective_to TEXT;
ALTER TABLE price_overrides ADD COLUMN IF NOT EXISTS active       INTEGER NOT NULL DEFAULT 1;
ALTER TABLE price_overrides ADD COLUMN IF NOT EXISTS billing_type TEXT NOT NULL DEFAULT 'ADHOC_PAPERWORK';
ALTER TABLE price_overrides ADD COLUMN IF NOT EXISTS source       TEXT NOT NULL DEFAULT 'CSM_OVERRIDE';

-- ------------------------------------------------------------------ audit log
-- override_audit covered price confirmations only. This covers every action
-- that changes what gets billed or who approved it. Append-only by convention;
-- nothing in the app issues UPDATE or DELETE against it.
CREATE TABLE IF NOT EXISTS audit_log (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  actor        TEXT,                 -- authenticated identity, or 'system:cron'
  action       TEXT NOT NULL,
  period_id    INTEGER REFERENCES periods(id) ON DELETE SET NULL,
  billing_type TEXT,
  customer     TEXT,
  account_id   TEXT,
  entity       TEXT,                 -- table/kind the id refers to
  entity_id    TEXT,
  previous_value TEXT,
  new_value      TEXT,
  source       TEXT,                 -- 'ui' | 'cron' | 'api' | 'seed'
  note         TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_period ON audit_log(period_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log(action, id DESC);

-- --------------------------------------------------------------- run metrics
-- pipeline_runs already recorded start/finish/status/stats. These are the
-- monthly run-log fields, kept on the same row so a run has one record rather
-- than a pipeline half and a reporting half.
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS run_type              TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS actor                 TEXT;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS rows_pulled           INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS rows_excluded         INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS duplicates_removed    INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS final_event_count     INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS customer_count        INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS unresolved_pricing    INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS unresolved_exceptions INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS expected_amount       DOUBLE PRECISION;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS notification_status   TEXT;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS events_added          INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS events_updated        INTEGER;
ALTER TABLE pipeline_runs ADD COLUMN IF NOT EXISTS events_disqualified   INTEGER;

-- ------------------------------------------------------ notification history
-- `kind` distinguishes the once-per-period scheduled review notification from
-- deliberate resends. The partial unique index below is what stops a retrying
-- cron job notifying @csms twice; a resend is a different kind and is free to
-- repeat.
CREATE TABLE IF NOT EXISTS notifications (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id     INTEGER NOT NULL REFERENCES periods(id) ON DELETE CASCADE,
  kind          TEXT    NOT NULL DEFAULT 'review',   -- 'review' | 'review_resend'
  channel       TEXT,
  mode          TEXT,                                -- dry_run | dev | live
  status        TEXT    NOT NULL,                    -- sent | skipped | failed
  slack_ts      TEXT,
  message       TEXT,
  error         TEXT,
  actor         TEXT,
  run_id        INTEGER REFERENCES pipeline_runs(id),
  created_at    TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

-- One successful scheduled review notification per period. Partial, so failed
-- attempts can be retried and resends are unconstrained.
CREATE UNIQUE INDEX IF NOT EXISTS idx_notify_once
  ON notifications(period_id, kind)
  WHERE kind = 'review' AND status = 'sent';

CREATE INDEX IF NOT EXISTS idx_notify_period ON notifications(period_id, id DESC);
